basePath: /api/v1
definitions:
  errcode.InternalError:
    properties:
      code:
        example: 200
        type: integer
      data: {}
      msg:
        example: ok
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /api/v1/tag:
    post:
      parameters:
      - description: Name
        in: body
        name: name
        required: true
        schema:
          type: string
      - description: State
        in: body
        name: state
        schema:
          type: integer
      - description: CreatedBy
        in: body
        name: created_by
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
        "400":
          description: error
          schema:
            type: string
      summary: 新增文章标签
  /tag/{id}:
    get:
      consumes:
      - application/json
      description: get tag by ID
      parameters:
      - description: Tag ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/errcode.InternalError'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errcode.InternalError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errcode.InternalError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errcode.InternalError'
      summary: Show an tag
      tags:
      - tag
swagger: "2.0"
